### ISSUE TITLE
Can we use Function App Host Config Sources instead of rebuilding the configuration?

### ISSUE THREAD

**Issue by gopalareddyms** [damienaicheh/Func.LoadSettings.Json#1]
Not really an issue, but wanted to get your thoughts why we can't relay on Function App Host Config Sources?

Function App Host loads bunch of config sources (including appsettings.json) as shown in screenshot below. I couldn't figure out why appsettings.json is loaded. 

#### Function App Host Config Sources
![image](https://user-images.githubusercontent.com/112032221/187586612-50dadf8c-6dd9-45a0-858d-5e6c95d3b67f.png)

#### appsettings.json
![image](https://user-images.githubusercontent.com/112032221/187587130-1e419834-76eb-44c8-b8c7-d28159b221c2.png)

#### appsettings.json Properties
![image](https://user-images.githubusercontent.com/112032221/187587221-f0228480-c609-4bf2-8a7c-b3969bfc30cf.png)

**Comment by damienaicheh** [comment]
Sorry I never use Function App Host Config Sources in my project so I can't answer directly like this. Hope you will find a solution.
