### ISSUE TITLE
how to publish this to azure?

### ISSUE THREAD

**Issue by DohmenICT** [damienaicheh/Func.LoadSettings.Json#2]
Hi, this is awesome. I now can use my local settings via dependency injection.

But what I can't seem to figure out is how do I get that separate section from my local.settings.json published to the settings.json in azure. This extra section is always missing when published. Do you have a hint for that?

**Comment by damienaicheh** [comment]
Hi,

Thanks.

Yes you must do a script in your CI / CD pipelines to automatically inject those values in the settings.json if there are no secret in there OR in the environment variables of your Azure Function

**Comment by DohmenICT** [comment]
Thanks for your quick reply! That makes sense. 
Do you know if this is something that I can configure in the VisualStudio publish settings of the APP or do I need to do that somewhere else?

**Comment by damienaicheh** [comment]
I don't think you have this kind of options in VisualStudio directly, I think you will have no choice to go the the Azure Portal and edit your Function Settings directly.

Good luck!

**Comment by DohmenICT** [comment]
thanks!
